### PR TITLE
\texdimenbothbpmm, \texdimenbothmmbp, \texdimenbothbpmmpt, \texdimenbothbpmmsp

### PR DESCRIPTION
**Pull request by jfbu**
Relates #10

barely tested (I also have to transfer the .transcript file into unit tests)

### CODE REVIEW

**Comment by jfbu** [comment]
@RuixiZhang42 I have implemented `\texdimenbothbpmm`, but not tested it enough.

**Comment by RuixiZhang42** [comment]
@jfbu The following doesn't make sense:
https://github.com/jfbu/texdimens/blob/1b1251411c65a6561f4044c41ee524526f94d30b/texdimens/texdimens.tex#L442-L447
The input `\texdimenbothbpmm{<negative dimen>}` then leads to `-\texdimenbothbpmm_a{}<number>;`, and so `#1` of `\texdimenbothbpmm_a` is `{}<number>`.

**Comment by jfbu** [comment]
@RuixiZhang42 thanks! Fixed. The bug came from a copy paste from `\texdimenwithunit_B` fork template

**Comment by RuixiZhang42** [comment]
`\texdimenbothmmbppt` and `\texdimenbothmmbpsp` are feeling left out… Let’s define them with `\let` (pun intended).

**Comment by jfbu** [comment]
> `\texdimenbothmmbppt` and `\texdimenbothmmbpsp` are feeling left out… Let’s define them with `\let` (pun intended).

Done ;-)

**Comment by RuixiZhang42** [comment]
Also in the documentation, for all “both” macros, the description “[…] is the largest dimension smaller than the original one […]” isn’t quite true. `Smaller than` means `<`; `not exceeding` means `<=`.

**Comment by jfbu** [comment]
Thanks, this is because I am French. We are very inclusive people.

**Comment by RuixiZhang42** [comment]
> Thanks, this is because I am French. We are very inclusive people.

LOL. When I learned the term “increasing function”, I was taught it meant “non-decreasing function”. So when you described the sequence `0<=floor(phi)<=floor(2*phi)<=...` being “increasing”, I understood it as “non-decreasing” perfectly well. I guess this makes two of us. :)

**Comment by jfbu** [comment]
I will merge this, even though I unit tests are somewhat insufficient in coverage. Thanks for great help.

**Pull request merged**
